config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def create
    @article = Article.create(article_params)
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def show
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(article_params)
    @article.update
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to :articles
  end

  private

  def article_params
    params.require(:articles).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= form_for(@article) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.submit %>
<% end %>

<%= link_to "Back", articles_path%>

app/views/articles/index.html.erb
<% @articles.each do |article|%>
<div class="article">
  <h2><%= link_to article.title, article_path(article) %></h2>
  <div class="d-flex justify-content-between align-items-start">
    <p><%= article.content[0..60] %>...</p>
    <%= link_to "Delete", article_path(article), class:"delete",
          method: :delete,
          data: { confirm: "Are you sure?" }  %>
  </div>
</div>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_for(@article) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.submit %>
<% end %>

<%= link_to "Back", articles_path%>

app/views/articles/show.html.erb
<div style="border-bottom: 1px solid #eeeeee">
  <h1><%= @article.title %></h1>
  <%= link_to "Edit Article", edit_article_path(@article)%>
  <%= link_to "Destroy Article", article_path(@article),
      method: :delete,
      data: { confirm: "Are you sure?" }  %>
  <%= link_to "Back to list", articles_path %>
</div>


<p><%= @article.content %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="">
  </head>

  <body>
    <header>
      <nav class="navbar d-flex align-items-center p-3">
        <div class="container-fluid">
            <a class="nav-title" href="/articles">Wikinimous</a>
            <a class="nav_link" href="/articles/new">New Article</a>
        </div>
      </nav>
      <div class="mb-3" style="border-bottom:1px solid #eeeeee"></div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>